### ISSUE TITLE
Set Version

### ISSUE THREAD

**Issue by ralphievolt** [disney/meteor-base#16]
Where should I define the version to build for my app when i run `docker-compose up`?

My app in running METEOR@1.8.1

**Comment by GeoffreyBooth** [comment]
In the `FROM` line of the Dockerfile. See https://github.com/disney/meteor-base/blob/master/README.md

**Comment by ps23** [comment]
```
FROM geoffreybooth/meteor-base:1.8.1
```

or something like this if not using the existing base Dockerfile:

```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        METEOR_VERSION: 1.8.1
```
