### ISSUE TITLE
MONGO_URL not working with Atlas

### ISSUE THREAD

**Issue by genesisapp-dev** [disney/meteor-base#179]
It seems like there is an issue when connecting to MongoDB Atlas using the **MONGO_URL:**

I am using the `docker-compose.yaml` file specified in https://github.com/disney/meteor-base/issues/82#issuecomment-889550017

However, the container always connects to the local DB instance of mongo DB.

Could it be related to the warning I am getting in the console when the container is started?

`(node:8) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized`

I tried the suggestions from StackOverflow:

https://stackoverflow.com/questions/53266471/saslprep-warning-when-using-mongoclient-connect/57234317#57234317

But the warning persists and the container will **_not_** connect to the Atlas DB.

Any ideas what the problem might be?

```yaml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb+srv://user_name:password@<atlas_cluster_url>/databaseName?retryWrites=true&w=majority
      PORT: 3000
```

Thanks.
