### ISSUE TITLE
How to use Mongorestore

### ISSUE THREAD

**Issue by elcronos** [disney/meteor-base#77]
Hi,

First thanks so much for creating this great repo. So far I have followed the steps on the README and have been able to run my container without problems. Now I would like to populate the database with some data when deploying. In my local computer I usually run this command :
```mongorestore -h 127.0.0.1 --port 3001 -d meteor --drop dump/meteor```
where dump/meteor is the folder that contains my backup. This command would need to execute after mongo and meteor are up. Any suggestion on how I can implement this using your scripts?

**Comment by ps23** [comment]
A general solution we use is to run a second container on the side. That container is a wait-for-it one (just google that to find implementations in multiple languages, I can share ours privately if you want), so it has an internal wait loop script to check if the db is up which we can configure. If the connection is successful, we run the command against the db. Here the docker-compose example:

```
mongoClientTemp:
    container_name: mongoClientTemp
    command:
      - /bin/sh
      - -c
      - |
          while /bin/true; do
          mongo -u ${MONGODB_USERNAME} -p ${MONGODB_PASSWORD} --host valcri-mongodb --port ${MONGODB_PORT_INT} --eval "db.getSiblingDB('meteor').createUser({user:'${MONGO_USER}', pwd:'${MONGO_PWD}', roles:[{role:'readWrite',db:'meteor'}]});" && break
          sleep 5                                                                                                                              
          done
    depends_on:
      - mongodb
    environment:
      - WAIT_HOSTS_TIMEOUT=120 
      - WAIT_SLEEP_HOSTS=5 
      - WAIT_BEFORE_HOSTS=5
      - WAIT_HOSTS=${MONGODB_HOSTNAME}:${MONGODB_PORT}
    image: ${CI_REGISTRY}/mongo-client:${MONGODB_VERSION}
    networks:
      - mongonetwork

```
