### ISSUE TITLE
Issue with external mongodb

### ISSUE THREAD

**Issue by inoyatov** [disney/meteor-base#82]
I followed examples and build my image. When I run two services `app` and `mongo` it works as expected. However, when I remove mongo service and dependence from app service it gave me an error as follows even If I passed the correct MONGO_URL.
```
Connecting to MongoDB...
(node:7) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Successfully connected to MongoDB
Starting app...
(node:1) [DEP0131] DeprecationWarning: The legacy HTTP parser is deprecated.
/opt/bundle/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at Timeout._onTimeout (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:439:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    setName: 'rs0',
    maxSetVersion: 1,
    maxElectionId: ObjectID {
      _bsontype: 'ObjectID',
      id: Buffer(12) [Uint8Array] [
        127, 255, 255, 255, 0,
          0,   0,   0,   0, 0,
          0,  20
      ]
    },
    servers: Map {
      '127.0.0.1:27017' => ServerDescription {
        address: '127.0.0.1:27017',
        error: Error: connect ECONNREFUSED 127.0.0.1:27017
            at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
          name: 'MongoNetworkError'
        },
        roundTripTime: -1,
        lastUpdateTime: 1162875703,
        lastWriteDate: null,
        opTime: null,
        type: 'Unknown',
        topologyVersion: undefined,
        minWireVersion: 0,
        maxWireVersion: 0,
        hosts: [],
        passives: [],
        arbiters: [],
        tags: []
      }
    },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: 9
  }
}
```

**Comment by diavrank** [comment]
I think you shouldn't remove mongo service, since Meteor app needs to connect to a database, that's why you are getting that error.

**Comment by inoyatov** [comment]
@diavrank i already removed. There is only one service `app` with external `MONGO_URL=mongodb://root:password@192.168.0.100:27017/meteor. But error shows me that I am trying to connect `127.0.01:27017`. So, what can be the case?

**Comment by diavrank** [comment]
I don't know why you remove the mongo service. I imagine that you have a meteor app which doesn't need a database (maybe because is only a website or front-end app), so, in that case you can use `MONGO_URL=none` according to this [link](https://stackoverflow.com/a/33978794/5051711)

**Comment by inoyatov** [comment]
@diavrank my MongoDB is managed instance I do not need to deploy it as docker. So, I removed it.

**Comment by inoyatov** [comment]
Here is my docker-compose.
```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://root:password@192.168.0.100:27017/meteor
      PORT: 3000
```

**Comment by diavrank** [comment]
ok, now I understand, so, in that case you need to specify a **public IP address or domain** in order to establish a successful connection, since if you use a local IP address like **192.168.0.100**, docker will try to find it inside the docker network (a network created by default which is used by the containers defined in the docker-compose file). Your compose file should be like this:

```yaml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://root:password@yourdomain.com:27017/meteor?authSource=admin
      PORT: 3000
```

Also, you can use a cloud service like Mongo Atlas, and youy compose file should be like this:

```yaml

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb+srv://user:password@cluster0.szdte.mongodb.net/databaseName?retryWrites=true&w=majority
      PORT: 3000
```

In my opinion, I don't recommend you to use Mongo Atlas in free tier because you can experience speed issues with your app. 

On the other hand, I recommend you if you are using docker in you personal computer, you'll need to migrate the database server to a docker container in order to achieve the connection with you app service. I don't know if exists a way to connect a docker container with a service in the host machine.
