### ISSUE TITLE
What are params for 

### ISSUE THREAD

**Issue by adamgins** [disney/meteor-base#86]
HI thanks heaps for this image. 

What should params/Dockerfile look like if I am just running this in my Meteor project folder and the Dockerfile, docker-compose.yml files are directly in the that folder?

BTW. I am on Meteor 2.3.5.. but was getting a not found so tried using 2.3.4 image below

Here are the files

Dockerfile:

```
FROM geoffreybooth/meteor-base:2.3.4

# Copy app package.json and package-lock.json into container
#COPY ./package*.json $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-app-npm-dependencies.sh

# Copy app source into container
COPY ./ $APP_SOURCE_FOLDER/

RUN bash $SCRIPTS_FOLDER/build-meteor-bundle.sh


# Use the specific version of Node expected by your Meteor release, per https://docs.meteor.com/changelog.html; this is expected for Meteor 2.3.5
FROM node:14.17.5-alpine

ENV APP_BUNDLE_FOLDER ./
ENV SCRIPTS_FOLDER ./

# Install OS build dependencies, which stay with this intermediate image but don’t become part of the final published image
RUN apk --no-cache add \
	bash \
	g++ \
	make \
	python

# Copy in entrypoint
COPY --from=0 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle
COPY --from=0 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

RUN bash $SCRIPTS_FOLDER/build-meteor-npm-dependencies.sh --build-from-source


# Start another Docker stage, so that the final image doesn’t contain the layer with the build dependencies
# See previous FROM line; this must match
FROM node:14.17.5-alpine

ENV APP_BUNDLE_FOLDER ./
ENV SCRIPTS_FOLDER ./

# Install OS runtime dependencies
RUN apk --no-cache add \
	bash \
	ca-certificates

# Copy in entrypoint with the built and installed dependencies from the previous image
COPY --from=1 $SCRIPTS_FOLDER $SCRIPTS_FOLDER/

# Copy in app bundle with the built and installed dependencies from the previous image
COPY --from=1 $APP_BUNDLE_FOLDER/bundle $APP_BUNDLE_FOLDER/bundle/

# Start app
ENTRYPOINT ["/docker/entrypoint.sh"]

CMD ["node", "main.js"]
```

Docker -compose.yml:

```
version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      - mongo
    environment:
      ROOT_URL: http://localhost
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:
```
